name: pinkora_ecommerce
description: Pinkora - Shop Your Happiness
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  shared_preferences: ^2.2.2

  # HTTP
  dio: ^5.4.0

  # UI
  card_swiper: ^3.0.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9

  # Icons
  iconsax: ^0.0.8

  # Fonts
  google_fonts: ^6.1.0

  # Utils
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/